// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/vinbyte/protip-golang-testing/domain"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, userID
func (_m *UserRepository) Fetch(ctx context.Context, userID int) ([]domain.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 []domain.User
	if rf, ok := ret.Get(0).(func(context.Context, int) []domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
