version: '3'
services:
  app:
    container_name: app1
    build: .
    env_file:
      - .env.docker
    ports: 
      - 9090:9090 
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: db-app1
    env_file:
      - .env.docker
    ports:
      - '5433:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/1-setup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5